common/urls.py
from django.urls import path
from . import views


app_name = 'common' # for redirection purpose

urlpatterns=[
    
    path('',views.home,name='home'),
    path('common_admin',views.admin, name='admin_login'),
    path('common_custlog',views.customer_login ,name='customer_login'),
    path('common_custsig',views.customer_signup, name='customer_signup'),
    path('common_sellerlog',views.seller_login,name='seller_login'),
    path('common_sellersig',views.seller_signup,name='seller_signup'),
    path('conditions_loop',views.conditions_loop,name='conditions_loop'),
    path('dom',views.dom,name='dom'),
    
]

customer/urls.py
from django.urls import path
from . import views




urlpatterns=[
    path('customer_home',views.cust_home),
    path('customer_mycart',views.cust_cart),
    path('customer_cart',views.cust_carts),
    path('customer_products',views.cust_product),
    path('customer_profits',views.cust_profit),
    path('customer_changes',views.cust_change),
    path('customer_css',views.cust_css),
    path('customer_cssbox',views.cust_cssbox),
    path('customer_csspro',views.cust_csspro),
    path('customer_csspos',views.cust_csspos),
    path('customer_csssticky',views.cust_csssticky),
    path('customer_cssflexbox',views.cust_csssflexbox),
    path('customer_cssgrid',views.cust_csssgrid),
    path('customer_cssgrid1',views.cust_csssgrid1),
    path('customer_cssgrid1',views.cust_csssgrid2),
    path('customer_bootstrap',views.cust_bootstrap),
    path('customer_sample_bootstrap',views.cust_sample_bootstrap),
     path('customer_grid_bootstrap',views.cust_grid_bootstrap),
      
    
    
]

ecomadmin/urls.py
from django.urls import path,include
from . import views




urlpatterns=[
    path('admin_home',views.admin_home),
    path('approve_sell',views.approve_sell),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('',include('common.urls')),
    path('seller/',include('seller.urls')),
    path('ecomadmin/',include('ecomadmin.urls'))
    
]

seller/urls.py
from django.urls import path,include
from . import views




urlpatterns=[
    path('sellers_home',views.seller_home),
    path('add_product',views.add_product),
     path(' profit',views. profit),
      path('changeproduct',views.changeproduct),
]

common/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models

# Create your models here.

ecomadmin/models.py
from django.db import models

# Create your models here.

seller/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render

# Create your views here.


def admin(request):
    return render(request,'common/admin_login.html')
    
def customer_login(request):
    return render(request,'common/customer_login.html')  

def customer_signup(request):
     return render(request,'common/customer_signup.html')         

def home(request):
     return render(request,'common/projecthome.html')   

def seller_login(request):
     return render(request,'common/sellerlog.html')         

def seller_signup(request):
     return render(request,'common/sellersig.html') 
     
def conditions_loop(request):
     return render(request,'common/conditions_loop.html')          

def dom(request):
     return render(request,'common/dom.html')                  

customer/views.py
from django.shortcuts import render

# Create your views here.
def cust_home(request):
    return render(request,'customer/home.html')
    
def cust_cart(request):
    return render(request,'customer/mycart.html')  

def cust_carts(request):
     return render(request,'customer/cart.html')         

def cust_product(request):
     return render(request,'customer/product_details.html')   

def cust_profit(request):
     return render(request,'customer/profit.html')         

def cust_change(request):
     return render(request,'customer/change.html')  
                 
def cust_css(request):
     return render(request,'customer/css.html')              
       
def cust_cssbox(request):
     return render(request,'customer/cssbox.html')              

def cust_csspro(request):
     return render(request,'customer/csspro.html')            

def cust_csspos(request):
     return render(request,'customer/position_relation.html')                 

def cust_csssticky(request):
     return render(request,'customer/positionsticky.html')

def cust_csssflexbox(request):
     return render(request,'customer/css_flexbox.html')                     

def cust_csssgrid(request):
     return render(request,'customer/cssgrid.html')        

def cust_csssgrid1(request):
     return render(request,'customer/cssgrid1.html') 

def cust_csssgrid2(request):
     return render(request,'customer/cssgrid2.html')       

def cust_bootstrap(request):
     return render(request,'customer/bootstrap.html')                                 

def cust_sample_bootstrap(request):
     return render(request,'customer/sample_bootstrap.html')   

def cust_grid_bootstrap(request):
     return render(request,'customer/grid_bootstrap.html')                                 

ecomadmin/views.py
from django.shortcuts import render

# Create your views here.


def admin_home(request):
    return render(request,'ecomadmin/home.html')



def approve_sell(request):
    return render(request,'ecomadmin/approve_seller.html')

seller/views.py
from django.shortcuts import render

# Create your views here.

def seller_home(request):
    return render(request,'seller/home.html')



def add_product(request):
    return render(request,'seller/add_product.html')



def profit(request):
    return render(request,'seller/profit.html')


def changeproduct(request):
    return render(request,'seller/change_product.html')

common/templates/common/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>admin login</h1>
</body>
</html>

common/templates/common/conditions_loop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="{% static 'js/conditions.js' %}"></script>
    <script src="{% static 'js/loop.js' %}"></script>
    <script src="{% static 'js/events.js' %}"></script>
</head>
<body>
    <h1>conditions & loops</h1>




    <h1>Html events</h1>
    
    <!-- <body onload="window.alert('Page successfully loaded');">   -->

    <input type="button" onclick="clickevent()" value="Click Here" />
    <br /><br />

    <p onmouseover="mouseoverevent()">Keep cursor over me</p>
    <br /><br />

    <input type="text" id="input1" onfocus="focusevent()" /> <br /><br />

    <input type="text" id="input1" onkeydown="keydownevent()" /> <br /><br />

    <p>
      Modify the text in the input field, then click outside the field to fire
      the onchange event.
    </p>

    Enter some text:
    <input
      type="text"
      name="txt"
      value="Hello"
      onchange="onchangeevent(this.value)"
    />

    <br /><br />
    <br />

    <p>
      Event will be fired when the input element lose focus after value update.
    </p>
    <input type="text" name="txt" value="" onchange="myFunction(this.value)" />
    <p id="show"></p>

</body>
</html>

common/templates/common/customer_login.html
{% extends 'common\master.html' %}
{% block content %}
<body>
   
    
    <table align="center" border="1px" width="60%" height="50%" style="color:aqua"><form action="">
        <tr>
            <td colspan="2" align="center">
            <h1>login</h1>
        </td>
        </tr>
        <tr>
            <td width="30%"> <label for=""> user name:</label></td>
            <td width="80%"><input type="text" placeholder="enter your name" size="15" maxlenght="15"> </td>
                       
        </tr>
        <tr>
            <td width="30%"> <label for=""> passward:</label></td>
            <td width="80%"><input type="password" size="15" maxlenght="15"> </td>
                       
        </tr>
        <tr>
            <td width="30%">
                <input type="submit">

        </tr>
        <tr>
            <td align="center" colspan="2"> <a href="{% url 'common:customer_signup' %}">already exit account</a></td>
        </tr>
    </form>

    </table>
    </body>

   
    {% endblock %}

common/templates/common/customer_signup.html
{% extends 'common\master.html' %}
{% block content %}

<body>
    <table align="center" border="1px" width="60%" height="50%" style="color:aqua"><form action="">
        <tr>
            <td colspan="2" align="center">
            <h1>FROM</h1>
        </td>
        </tr>
        <tr>
            <td width="30%"> <label for="">  name:</label></td>
            <td width="80%"><input type="text" placeholder="enter your name" size="15" maxlenght="15"> </td>
                       
        </tr>
        <tr>
            <td width="30%"> <label for=""> email id:</label></td>
            <td width="80%"><input type="email" size="15" maxlenght="15"> </td>
                       
        </tr>
        <tr>
            <td width="30%"> <label for=""> phone number:</label></td>
            <td width="80%"><input type="phone" size="15" maxlenght="15"> </td>
                       
        </tr>
       
        <tr>
            <td width="30%">
                <input type="submit">
    
        </tr>
        <tr>
            <td align="center" colspan="2"> <a href="{% url 'common:customer_login' %}">signin</a></td>
        </tr>
    </form>
    
    </table>
    
    </body>

{% endblock %}

common/templates/common/dom.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="{% static 'js/dom.js' %}"></script>
</head>

<body>


    <h1 id="heading">Lorem, ipsum dol amet consectetur</h1>
    <p class="content">Lorem ipsum dolor sit amet.</p>
    <p class="content">Lorem ipsum dolor sit amet consectetur.</p>
    <button onClick="change()">Clickme</button>



    <script>
        console.log(document.getElementById('heading'));
        console.log(document.getElementsByTagName('p'));
        console.log(document.getElementsByClassName('content'));

        function change() {
            document.getElementById('heading').innerHTML = "dfgdgtyfkncgythbbkyz";

        }

    </script>


</body>

</html>

common/templates/common/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
        <nav style="background: rgb(131, 173, 201);">
        
    <a href="{% url 'common:admin_login' %}">Admin login</a>
    <a href="{% url 'common:customer_login' %}">Customer login</a>
    <a href="{% url 'common:customer_signup' %}">Seller Login</a>

        </nav>
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <div>
        <footer>
            <li>happy </li>

        </footer>
    </div>
</body>
</html>

common/templates/common/projecthome.html
{% extends 'common/master.html' %}
{% load static %}

 
{% block content %}
    
    <img src="{% static 'images/lap.jpg' %}" height="200px" alt="">
 
    {% endblock %}

common/templates/common/seller_login.html
{% extends 'common/master.html' %}
{% load static %}
     

{% block content %}

<img src="{% static 'images/lap.jpg' %}" height="200px" alt="">
 
{% endblock %}

common/templates/common/seller_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>seller signup</h1>
</body>
</html>

customer/templates/customer/bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Import boostrp framework -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<!-- Navigation bar at the top -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="#">
    <img src="{% static 'image/lap.jpg' %}" width="50">
  </a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="#">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Courses</a>
    </li>

    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Technologies
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">HTML </a>
        <a class="dropdown-item" href="#">CSS </a>
        <a class="dropdown-item" href="#">JavaScript </a>
      </div>
    </li>
  </ul>
</nav>
<!-- Navigation bar ends here -->
<!-- Banner at the top(Jumbotron) -->
<div class="jumbotron text-center">
  <h1>Cybersquare - Design Your Website</h1>
  <p>Users to creators of technology!</p> 
</div><!-- End Jumbotron -->
  
<!-- Container class starts here. Normally in a bootstrap page contents are kept inside contaner division -->
<div class="container">
  <div class="row">
    <!-- A bootstrap page is divided into 12 equal columns -->
    <!-- col-sm-4 - Occupies 3 columns upto small sixze. Columns are stacked below this size. screen sizes are lg, md, sm and xs-->
    <div class="col-sm-4">
      <h3>HTML</h3><hr>
      <p><img src="{% static 'image/lap.jpg' %}" class="img-fluid "></p>
      <p>Hypertext Markup Language is the standard markup language for documents designed to be displayed in a web browser.</p>
    </div>
    <div class="col-sm-4">
      <h3>CSS</h3><hr>
      <p><img src="{% static 'image/lap.jpg' %}" class="img-fluid"></p>
      <p>Cascading Style Sheets is a style sheet language used for describing the presentation of a document written in a markup language such as HTML.</p>
    </div>
    <div class="col-sm-4">
      <h3>JavaScript</h3><hr>        
      <p><img src="{% static 'image/lap.jpg' %}" class="img-fluid rounded"></p>
      <p>JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification. JavaScript is high-level, often just-in-time compiled, and multi-paradigm. It has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions.</p>
    </div>
  </div>
</div>

</body>
</html>

customer/templates/customer/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>cart</h1>
</body>
</html>

customer/templates/customer/change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>change password</h1>
</body>
</html>

customer/templates/customer/cssbox.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>box model</title>
    <link rel="stylesheet" href="{% static 'css/cssbox.css'%}">
    <style>
        h1{
    background-color: blue;
    color: black;
   /* margin: 50px;
    padding: 50px;
    margin: 20px 50px 150px 300px;
    margin: 50px 500px;*/
    margin-top: 100px;
    margin-left: 300px;
    margin-right: 159px;
    border:3px solid black;
    padding-top: 200px;
    padding-left: 300px;
}
    </style>
</head>
<body>
    <h1>css box</h1>
    
</body>
</html>

customer/templates/customer/cssgrid.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>grid</title>
    <style>
        .container{
            background-color: blueviolet;
            display: grid;
            grid-template-columns: auto auto auto;
            grid-template-rows: auto auto;
            grid-gap: 20px 5px;
            padding: 20px;
        }
        .container div{
            padding: 10px;
        }
        .item{
            background-color: antiquewhite;
            border: 1px solid red;
            height: auto;
        }
        .a{
            /* grid-column-start: 2; */
            /* grid-column-end: 4; */

            /* grid-column: 1/3; */

            /* grid-row-start: 1; */
            /* grid-row-end: 3; */

            /* grid-row: 1/4; */

            /* grid-column: 2/span 2; */

            /* grid-row: 1/span 2; */

            grid-area: 1/1/3/4;
        }

    </style>
</head>
<body>
    <!-- <div class="container">
        <div class="item">1</div>
        <div class="item">2</div>
        <div class="item">3</div>
        <div class="item">4</div>
        <div class="item">5</div>
        <div class="item">6</div>
    </div> -->

    <div class="container">
        <div class="item a">1</div>
        <div class="item b">2</div>
        <div class="item c">3</div>
        <div class="item d">4</div>
        <div class="item e">5</div>
        <div class="item f">6</div>
    </div>
</body>
</html>

customer/templates/customer/cssgrid1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cssgrid1</title>
    <style>
        .container {
            background-color: blueviolet;
            display: grid;
            grid-template-columns: auto auto auto;
            grid-template-rows: auto auto;
            grid-gap: 20px 5px;
            padding: 20px;
        }

        .container div {
            padding: 10px;
        }

        .h1 {
            background-color: antiquewhite;
            border: 1px solid red;
            height: auto;
        }

        .menu {
            background-color: antiquewhite;
            border: 1px solid red;
            height: auto;
        }

        .section1 {
            background-color: antiquewhite;
            border: 1px solid red;
            height: auto;

        }

        .section2 {
            background-color: antiquewhite;
            border: 1px solid red;
            height: auto;

        }

        .footer {
            background-color: antiquewhite;
            border: 1px solid red;
            height: auto;
        }
        .a{
            grid-area: 1/1/3/4;
        }
        .b{
            grid-area: 3/2/4/3;
            height: 200px;
        }
        .c{
             grid-area: 3/2/4/3;
            height: 200px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="h1 a">Heading</div>
        <div class="menu e">Menu</div>
        <div class="section1 b">Section1</div>
        <div class="section2 c">section2</div>
        <div class="footer d">footer</div>

    </div>


</body>

</html>

customer/templates/customer/csspro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>css properties</title>
    <link rel="stylesheet" href="{% static 'css/csspro.css' %}">
    <style>
       /* color properties*/
        h1{
            color:brown;
            /*visibility: hidden;*/
            display: none;

        }
        h2{
            color:#395943;
        }
        h3{
            color:rgb(120, 26, 99);
   
        }
        p{
            color:rgba(15, 43, 146, 0.6);
        }

        /*background properties*/
        body{
            height:fit-content;
           /* background-image: url("https://picsum.photos/id/1/200/300");*/
          /*    background-repeat: no-repeat; */
          /*background-repeat: repeat-x;*/
           /*background-repeat: repeat-y;;*/
          /* background-repeat: no-repeat;
           background-position: right top;
           background-size: cover;*/
        }
        /*font and text properties*/

        p{
            font-size:50px;
            font-style: italic;
            font-family: Arial, Helvetica, sans-serif;
            font-weight: bolder;
            text-align: center;
            text-decoration:underline;
            text-transform: uppercase;
        }
        marquee{
            color:blue;
        }
        /*overflow*/
        #overflow{
            height: 150px;
            width: 200px;
            border:5px solid blueviolet;
            background-color: blue;
            color:bisque;
        
            overflow: scroll;
            overflow:auto;
            box-shadow: 20px 40px 60px 20px royalblue;
            margin-bottom: 100px;
        }
        a:visited{
            color: #395943;
        }
        
        a:hover{
            color:blue;
        }
        input:focus{
            color:rgb(64, 0, 255);
        }
        input::placeholder{
            color: aqua;
        }
        h2::first-letter{
            color:red;
        }

    </style>
</head>

<body>
    <h1>css properties</h1>
    <h2>css</h2>
    <h3>java</h3>
    <p>
        <marquee behavour="alternate" direction="left">Lorem ipsum dolor sit amet.</marquee>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores velit eligendi alias aliquid praesentium
        dolore.</p>
        <a href="#">Lorem,ipsum</a>
        <input type="text" placeholder="enter your name">
        <div id="overflow">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam ullam, aperiam sit id a et voluptatibus nemo esse libero! Hic consectetur sed qui nesciunt. Libero nostrum harum expedita, cupiditate consequatur ex aut aliquam. Ipsam, nesciunt, illum quo tempora enim blanditiis ex distinctio voluptas sunt obcaecati, ducimus repudiandae pariatur amet et.
        </div>


</body>

</html>

customer/templates/customer/grid_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        .container-fluid{
            background-color: blue;
        }

        #sec{
            background-color: aquamarine;
        }
        #thir{
            background-color: brown;
            height: 80px;
        }
        #img{
            height: 500px;
        }
    </style>
</head>


<body>
    <div class="container-fluid" >
        <div class="row">
            <div class="col-4">
                <h1>java</h1>
            </div>
            <div class="col-4">
                <h1>python</h1>
            </div>
            <div class="col-4">
                <h1>php</h1>
            </div>
            
        </div>

        <div class="row" id="sec">
            <div class="col-sm-3">
                <h1>java</h1>
            </div>
            <div class="col-sm-3">
                <h1>python</h1>
            </div>
            <div class="col-sm-3">
                <h1>php</h1>
            </div>
            <div class="col-sm-3">
                <h1>php</h1>
            </div>
            
        </div>

        <div class="row" id="thir">
            <div class="col-2">
                <h1>java</h1>
            </div>
            <div class="col-2">
                <!-- <h1>python</h1> -->
            </div>
            <div class="col-2">
                <!-- <h1>php</h1> -->
            </div>
            <div class="col-2">
                <!-- <h1>php</h1> -->
            </div>
            <div class="col-2">
                <h1>react</h1>
            </div>
            <div class="col-2">
                <h1>php</h1>
            </div>
        </div>

        <div class="row" id="img">
            <div class="col-md-4">
                <img src="{% static 'image/lap.jpg' %}" alt="" height="80px" width="80px">
            </div>
            <div class="col-md-4">
                <img src="{% static 'image/lap.jpg' %}" alt="" height="80px" width="80px">
            </div>
            <div class="col-md-4">
                <img src="{% static 'image/lap.jpg' %}" alt="" height="80px" width="80px">
            </div>
        </div>



    </div>

</body>

</html>

customer/templates/customer/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>home</h1>
   
</body>
</html>

customer/templates/customer/mycart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>welcome to cart</p>
</body>
</html>

customer/templates/customer/product_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>product details </h1>
</body>
</html>

customer/templates/customer/profit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>profit</h1>
</body>
</html>

ecomadmin/templates/ecomadmin/approve_seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>approve seller</h1>
</body>
</html>

ecomadmin/templates/ecomadmin/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>home</h1>
    <img src="{% static 'images/ac.jpg' %}">
</body>
</html>